# Generated by Django 4.2.5 on 2023-10-07 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlacesRating',
        ),
    ]
