# Generated by Django 4.2.5 on 2023-10-12 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_triptracker'),
        ('places', '0003_delete_placesrating'),
    ]

    operations = [
    ]
