# Generated by Django 4.2.5 on 2023-10-12 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0004_merge_0002_triptracker_0003_delete_placesrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacesRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')])),
                ('rating_date', models.DateTimeField(auto_now_add=True)),
                ('places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='places.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('places', 'user')},
            },
        ),
    ]
